import type { Vehicle, Location, MaintenanceRecord } from "@/types/fleet"

export const mockLocations: Location[] = [
  {
    id: "1",
    name: "Downtown Branch",
    address: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    phone: "(555) 123-4567",
    email: "downtown@fleetflow.com",
    isActive: true,
    vehicleCount: 45,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Airport Location",
    address: "JFK Airport Terminal 4",
    city: "Queens",
    state: "NY",
    zipCode: "11430",
    phone: "(555) 987-6543",
    email: "airport@fleetflow.com",
    isActive: true,
    vehicleCount: 78,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "3",
    name: "Service Center",
    address: "456 Industrial Blvd",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11201",
    phone: "(555) 456-7890",
    email: "service@fleetflow.com",
    isActive: true,
    vehicleCount: 12,
    createdAt: new Date("2024-02-01"),
  },
]

export const mockVehicles: Vehicle[] = [
  {
    id: "1",
    make: "Toyota",
    model: "Camry",
    year: 2023,
    licensePlate: "ABC-123",
    vin: "1HGBH41JXMN109186",
    category: "sedan",
    status: "available",
    location: "Downtown Branch",
    locationId: "1",
    pricePerDay: 45,
    pricePerWeek: 280,
    pricePerMonth: 1100,
    fuelType: "gasoline",
    transmission: "automatic",
    seats: 5,
    doors: 4,
    fuelCapacity: 60,
    currentFuelLevel: 85,
    mileage: 15420,
    features: ["Bluetooth", "GPS Navigation", "Backup Camera", "AC", "Cruise Control"],
    color: "Silver",
    lastMaintenanceDate: new Date("2024-11-01"),
    nextMaintenanceDate: new Date("2025-02-01"),
    maintenanceMiles: 20000,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-12-01"),
    totalBookings: 45,
    totalRevenue: 12500,
    images: ["/toyota-camry-sedan.png"],
    primaryImage: "/toyota-camry-sedan.png",
  },
  {
    id: "2",
    make: "Honda",
    model: "CR-V",
    year: 2022,
    licensePlate: "XYZ-789",
    vin: "2HGBH41JXMN109187",
    category: "suv",
    status: "rented",
    location: "Airport Location",
    locationId: "2",
    pricePerDay: 65,
    pricePerWeek: 420,
    pricePerMonth: 1650,
    fuelType: "gasoline",
    transmission: "automatic",
    seats: 7,
    doors: 4,
    fuelCapacity: 70,
    currentFuelLevel: 60,
    mileage: 28350,
    features: ["AWD", "Backup Camera", "Bluetooth", "AC", "Roof Rails"],
    color: "Blue",
    lastMaintenanceDate: new Date("2024-10-15"),
    nextMaintenanceDate: new Date("2025-01-15"),
    maintenanceMiles: 30000,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-01"),
    totalBookings: 67,
    totalRevenue: 18900,
    images: ["/honda-crv-suv.png"],
    primaryImage: "/honda-crv-suv.png",
  },
  {
    id: "3",
    make: "BMW",
    model: "X5",
    year: 2023,
    licensePlate: "BMW-456",
    vin: "3HGBH41JXMN109188",
    category: "luxury",
    status: "maintenance",
    location: "Service Center",
    locationId: "3",
    pricePerDay: 120,
    pricePerWeek: 780,
    pricePerMonth: 3000,
    fuelType: "gasoline",
    transmission: "automatic",
    seats: 7,
    doors: 4,
    fuelCapacity: 80,
    currentFuelLevel: 40,
    mileage: 8920,
    features: ["Leather Seats", "Premium Audio", "Navigation", "Panoramic Roof", "Heated Seats"],
    color: "Black",
    lastMaintenanceDate: new Date("2024-12-01"),
    nextMaintenanceDate: new Date("2025-03-01"),
    maintenanceMiles: 15000,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-12-01"),
    totalBookings: 23,
    totalRevenue: 8900,
    images: ["/bmw-x5-luxury-suv.png"],
    primaryImage: "/bmw-x5-luxury-suv.png",
  },
  {
    id: "4",
    make: "Tesla",
    model: "Model 3",
    year: 2023,
    licensePlate: "TSL-321",
    vin: "4HGBH41JXMN109189",
    category: "electric",
    status: "available",
    location: "Downtown Branch",
    locationId: "1",
    pricePerDay: 85,
    pricePerWeek: 550,
    pricePerMonth: 2100,
    fuelType: "electric",
    transmission: "automatic",
    seats: 5,
    doors: 4,
    fuelCapacity: 75, // kWh for electric
    currentFuelLevel: 92,
    mileage: 12500,
    features: ["Autopilot", "Premium Audio", "Supercharging", "Glass Roof", "Mobile Connector"],
    color: "White",
    lastMaintenanceDate: new Date("2024-11-15"),
    nextMaintenanceDate: new Date("2025-05-15"),
    maintenanceMiles: 25000,
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date("2024-12-01"),
    totalBookings: 34,
    totalRevenue: 11200,
    images: ["/tesla-model-3.png"],
    primaryImage: "/tesla-model-3.png",
  },
]

export const mockMaintenanceRecords: MaintenanceRecord[] = [
  {
    id: "1",
    vehicleId: "3",
    type: "routine",
    description: "Oil change and tire rotation",
    cost: 150,
    performedBy: "Mike Johnson",
    performedAt: new Date("2024-12-01"),
    nextDueDate: new Date("2025-03-01"),
    nextDueMiles: 15000,
    status: "completed",
    notes: "All fluids checked and topped off",
  },
  {
    id: "2",
    vehicleId: "2",
    type: "repair",
    description: "Brake pad replacement",
    cost: 320,
    performedBy: "Sarah Wilson",
    performedAt: new Date("2024-11-20"),
    status: "completed",
    notes: "Front brake pads replaced, rotors resurfaced",
  },
  {
    id: "3",
    vehicleId: "1",
    type: "inspection",
    description: "Annual safety inspection",
    cost: 75,
    performedBy: "Auto Inspection Center",
    performedAt: new Date("2024-11-01"),
    nextDueDate: new Date("2025-11-01"),
    status: "completed",
    notes: "Passed all safety requirements",
  },
]
